import { createActions } from 'redux-actions'

export const {
  setCellState,
  saveNotebook,
  saveNotebookSuccess,
  newCell,
  deleteCell,
  splitCell,
  mergeCell,
  switchCell,
  changeCellContent,
  changeCellType,
  hideCellTextarea,
  hideAllCellTextarea,
  hideCell,
  hideAllCells,
  showCell,
  showAllCells,
  toggleAllCellTools,
  toggleCellLangOption,
  processCellCode
} = createActions({
  SET_CELL_STATE: state => state,
  SAVE_NOTEBOOK: () => undefined,
  SAVE_NOTEBOOK_SUCCESS: () => undefined,
  NEW_CELL: type => type,
  DELETE_CELL: id => id,
  SPLIT_CELL: id => id,
  MERGE_CELL: cellPositionIndex => cellPositionIndex,
  SWITCH_CELL: id => id,
  CHANGE_CELL_CONTENT: (id, content) => ({ id, content }),
  CHANGE_CELL_TYPE: (id, type) => ({ id, type }),
  HIDE_CELL_TEXTAREA: id => id,
  HIDE_ALL_CELL_TEXTAREA: () => undefined,
  HIDE_CELL: id => id,
  HIDE_ALL_CELLS: () => undefined,
  SHOW_CELL: id => id,
  SHOW_ALL_CELLS: () => undefined,
  TOGGLE_ALL_CELL_TOOLS: () => undefined,
  TOGGLE_CELL_LANG_OPTION: id => id,
  PROCESS_CELL_CODE: id => id
})
